# Generated by Django 2.2.1 on 2021-02-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210211_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Home Care', 'Home Care'), ('Electronics', 'Electronics'), ('Restuarants', 'Restuarants'), ('Banks', 'Banks'), ('Entertainment', 'Entertainment')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_image',
            field=models.URLField(),
        ),
    ]
