# Generated by Django 2.2.1 on 2021-02-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210211_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='mobile_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_image',
            field=models.URLField(blank=True),
        ),
    ]
