# Generated by Django 3.1.6 on 2021-02-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210217_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postproduct',
            name='product_type',
        ),
    ]
