# Generated by Django 3.1.6 on 2021-02-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_postproduct_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproduct',
            name='previous_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
