# Generated by Django 3.1.6 on 2021-03-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210314_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_image',
            field=models.FileField(blank=True, upload_to='profilePic'),
        ),
    ]
