# Generated by Django 3.1.6 on 2021-04-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210314_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='push_token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
