# Generated by Django 3.1.6 on 2021-04-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_post_firebase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='firebase_id',
        ),
        migrations.AddField(
            model_name='brand',
            name='firebase_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
