# Generated by Django 3.1.6 on 2021-04-19 12:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210410_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='newsLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='newsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('news_cover', models.URLField()),
                ('description', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='newsView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.newspost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
            ],
        ),
        migrations.DeleteModel(
            name='news',
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Home Care', 'Home Care'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('Cosmetics', 'Cosmetics'), ('Furniture', 'Furniture'), ('Beverages', 'Beverages')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='newslike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.newspost'),
        ),
        migrations.AddField(
            model_name='newslike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount'),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.newspost'),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount'),
        ),
    ]
